name: Deploy al Server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World"

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World 2"
        run: echo "Hello World 2"
