name: Deploy al Server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    env:
      NAME: "JOTA"
    steps:
      - name: "Workin dir"
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: "Workin dir after checkout"
        run: ls -al

  second_jobs:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World 2"
        run: echo "Hello World 2"
