name: Deploy al Server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: "JOTA"

    outputs:
      salida1: ${{ steps.dar_mensaje.outputs.my_variable }}

    steps:
      - name: "Workin dir"
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: "Workin dir after checkout"
        run: ls -al

      - name: "Variable de Entorno"
        run: echo $GITHUB_OUTPUT

      - name: "Dar mensaje"
        id: dar_mensaje
        run: echo my_variable= "Hola Jota Roncon" >> $GITHUB_OUTPUT

      - name: "Ver mensaje"
        run: echo "${{ steps.dar_mensaje.outputs.my_variable }}"
  second_jobs:
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      salidaAnterior: ${{ needs.first_jobs.outputs.salida1 }}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World 2"
        run: echo "$salidaAnterior"

  third_jobs:
    
    runs-on: ubuntu-latest

    steps:
      - name: "Generar archivo"
        run: |
          echo "Archivo de Prueba, Jota" >> test.log
      
      - name: "Subir artefacto"
        uses: actions/upload-artifact@v4
        with: 
          name: "artefacto-test"
          path: test.log

  fourth_jobs:
    
    runs-on: ubuntu-latest

    needs: third_jobs
    
    steps:
      - name: "Descargar artefacto"
        run: actions/download-artifact@v4
        with: 
          name: "artefacto-test"

      - name: "Ver contenido"
        run: cat test.log